name: Cameraman
version: 1.2.0

author: ChalkPE, VsrStudio
main: chalk\cameraman\Cameraman
api: [5.0.0]

website: http://chalk.pe
description: An automatic motion control plugin for PocketMine-MP 5

permissions:
  cameraman.use:
    description: Allows a player to use all features of Cameraman
    default: true

commands:
  camera:
    description: Manage your movement by Cameraman
    permission: cameraman.use
    usage: /camera or /cam
    aliases: [cam]
